export {default as Header } from './header/header'
export {default as MainContainer} from './MainComponent'
export {default as CreateContainer} from './createContainer'
export {default as Home} from './HOME'
export {default as Loader} from './loader'
export {default as CreateCatogery} from './createcatogery'
export {default as FruitSection} from './fruitsection'
export {default as RowContainer} from './Rowcontainer'
export {default as MenuSection} from './Menusection'
export {default as CartContainer} from './cartcontainer'
export {default as Footer} from './Footer'